"""
Artifact database model.

Represents a file or collection of files generated by a completed job.
Artifacts are stored on the server and can be downloaded later through
the API or dashboard.
"""

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from freight.db import Base


class Artifact(Base):
    """
    ORM model representing a job artifact.

    Every artifact belongs to exactly one job. A single job may generate
    multiple artifacts during its execution.
    """

    __tablename__ = "artifacts"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        index=True,
    )

    job_id: Mapped[int] = mapped_column(
        ForeignKey("jobs.id"),
        nullable=False,
    )

    path: Mapped[str] = mapped_column(
        String(500),
        nullable=False,
    )

    size: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    job = relationship(
        "Job",
        back_populates="artifacts",
    )